apiVersion: v1
kind: Service
metadata:
  name: underwriting-api
  labels:
    app.kubernetes.io/name: credit-underwriting-decision-graph
spec:
  selector:
    app.kubernetes.io/name: credit-underwriting-decision-graph
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
